// This file is automatically generated by the Firebase setup.
// Do not edit this file manually.
export const firebaseConfig = {"projectId":"studio-5756263585-a1419","appId":"1:659575247472:web:7bed858ce9a55f2e1edab5","storageBucket":"studio-5756263585-a1419.appspot.com","apiKey":"AIzaSyD8IwTEiYdB1RW1pRWkOddugnwtpVXU-pU","authDomain":"studio-5756263585-a1419.firebaseapp.com","messagingSenderId":"659575247472"};
